# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TaiwanRailWay.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 381)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 80, 111, 20))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox_2 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(100, 130, 111, 20))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(100, 170, 81, 20))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(100, 320, 33, 20))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.timeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(100, 210, 96, 20))
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.timeEdit_2 = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit_2.setGeometry(QtCore.QRect(100, 250, 96, 20))
        self.timeEdit_2.setObjectName(_fromUtf8("timeEdit_2"))
        self.comboBox_3 = QtGui.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(100, 280, 69, 20))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 71, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 47, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 47, 12))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 210, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 250, 61, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 290, 47, 12))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 320, 61, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(100, 20, 111, 21))
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 60, 231, 301))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 60, 221, 301))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(90, 70, 111, 20))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 120, 47, 12))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.dateEdit_2 = QtGui.QDateEdit(self.groupBox_2)
        self.dateEdit_2.setGeometry(QtCore.QRect(90, 110, 81, 20))
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.comboBox_5 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(90, 20, 111, 20))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 47, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 71, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.timeEdit_3 = QtGui.QTimeEdit(self.groupBox_2)
        self.timeEdit_3.setGeometry(QtCore.QRect(90, 150, 96, 20))
        self.timeEdit_3.setObjectName(_fromUtf8("timeEdit_3"))
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(20, 230, 47, 12))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(20, 190, 61, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(20, 260, 61, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.comboBox_6 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_6.setGeometry(QtCore.QRect(90, 220, 69, 20))
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(20, 150, 61, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.spinBox_2 = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_2.setGeometry(QtCore.QRect(90, 260, 33, 20))
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.timeEdit_4 = QtGui.QTimeEdit(self.groupBox_2)
        self.timeEdit_4.setGeometry(QtCore.QRect(90, 190, 96, 20))
        self.timeEdit_4.setObjectName(_fromUtf8("timeEdit_4"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 10, 81, 51))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(250, 20, 101, 16))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBox, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.dateEdit)
        MainWindow.setTabOrder(self.dateEdit, self.timeEdit)
        MainWindow.setTabOrder(self.timeEdit, self.timeEdit_2)
        MainWindow.setTabOrder(self.timeEdit_2, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.spinBox)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "身份證字號：", None))
        self.label_2.setText(_translate("MainWindow", "起站：", None))
        self.label_3.setText(_translate("MainWindow", "到站：", None))
        self.label_4.setText(_translate("MainWindow", "日期：", None))
        self.label_5.setText(_translate("MainWindow", "起始時間：", None))
        self.label_6.setText(_translate("MainWindow", "截止時間：", None))
        self.label_7.setText(_translate("MainWindow", "車種：", None))
        self.label_8.setText(_translate("MainWindow", "訂票張數：", None))
        self.groupBox.setTitle(_translate("MainWindow", "【出發／單程】", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "【回程】", None))
        self.label_9.setText(_translate("MainWindow", "日期：", None))
        self.label_10.setText(_translate("MainWindow", "到站：", None))
        self.label_11.setText(_translate("MainWindow", "起站：", None))
        self.label_12.setText(_translate("MainWindow", "車種：", None))
        self.label_13.setText(_translate("MainWindow", "截止時間：", None))
        self.label_14.setText(_translate("MainWindow", "訂票張數：", None))
        self.label_15.setText(_translate("MainWindow", "起始時間：", None))
        self.pushButton.setText(_translate("MainWindow", "開始訂票", None))
        self.checkBox.setText(_translate("MainWindow", "是否為來回票", None))
        self.menu.setTitle(_translate("MainWindow", "說明", None))
        self.action.setText(_translate("MainWindow", "使用方法", None))
        self.action_2.setText(_translate("MainWindow", "免責聲明", None))

